### ISSUE TITLE
Corrupted image upload

### ISSUE THREAD

**Issue by fueguino84** [atymic/twitter#222] opened 2018-01-14 13:37 UTC
It was working ok, I don't know why suddenly images upload are getting corrupted.

This is the code I'm using (IImage correspond to Intervention Image, used in order to post smaller images):

```
    protected function tweet(Image $image)
    {
        $reduced_image = IImage::make('storage/'.$image->filename)->widen(1024)->heighten(768)->encode('jpg', 75);
        $uploaded_media = Twitter::uploadMedia(['media' => $reduced_image->encoded]);
        try {
            return Twitter::postTweet(['status' => mb_strimwidth($image->description, 0, 100, '...'),
                                        'media_ids' => $uploaded_media->media_id_string,
                                        'lat' => $image->lat,
                                        'long' => $image->long]);
        } catch (\Exception $e) {
        }
    }
```

I tried also saving the image with intervention and uploading like this:

```
    protected function tweet(Image $image)
    {
        $reduced_image = IImage::make('storage/'.$image->filename)->widen(1024)->heighten(768)->encode('jpg', 75);
        $reduced_image->save('temp.jpg');
        $uploaded_media = Twitter::uploadMedia(['media' => file_get_contents(public_path('temp.jpg'))]);
        try {
            return Twitter::postTweet(['status' => mb_strimwidth($image->description, 0, 100, '...'),
                                        'media_ids' => $uploaded_media->media_id_string,
                                        'lat' => $image->lat,
                                        'long' => $image->long]);
        } catch (\Exception $e) {
        }
    }
```
But again, file gets saved ok to the storage but when uploading to twitter image get corrupted.

**Comment by atymic** [comment] 2019-11-07 10:17
Are you still having issues?

**Comment by atymic** [comment] 2020-06-22 01:15
Duplicate of #92

**Closed by atymic** 2020-06-22 01:15 UTC
Labels: bug
